In [1]:
import numpy as np

In [2]:
arr = np.array( [1,2,3,4.5,9,12] )
arr

array([ 1. ,  2. ,  3. ,  4.5,  9. , 12. ])

In [6]:
arr.dtype

dtype('float64')

In [3]:
arr.shape

(6,)

In [4]:
np.sum(arr)

31.5

In [5]:
np.mean(arr)

5.25

In [7]:
np.array( [1,2,3,4,9,12]  )

array([ 1,  2,  3,  4,  9, 12])

In [8]:
np.array( [1,2,3,4,9,12]  ).dtype

dtype('int32')

In [9]:
np.array( [1, "Darshan", 22.5]  )

array(['1', 'Darshan', '22.5'], dtype='<U11')

In [10]:
np.array( [1, "Darshan", 22.5]  ).dtype

dtype('<U11')

In [11]:
np.sum( np.array( [1, "Darshan", 22.5]  ) )

TypeError: cannot perform reduce with flexible type

In [12]:
np.array( [1, "Darshan", 22.5, 2+3j, True]  )

array(['1', 'Darshan', '22.5', '(2+3j)', 'True'], dtype='<U11')

In [13]:
np.array( [1, "Darshan", 22.5, 2+3j, True]  ).dtype

dtype('<U11')

In [14]:
arr

array([ 1. ,  2. ,  3. ,  4.5,  9. , 12. ])

In [15]:
arr.shape

(6,)

In [16]:
arr = np.array( [ [1,2,3], [4,5,6] ] )
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
arr.shape

(2, 3)

In [18]:
arr.dtype

dtype('int32')

In [19]:
arr[0]

array([1, 2, 3])

In [20]:
arr[1][2]

6

In [25]:
len(np.arange(12))

12

In [22]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
arr = np.arange(12).reshape(2,2,3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [27]:
arr[1]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [28]:
arr[1][0]

array([6, 7, 8])

In [29]:
arr[0][1][2]

5

In [30]:
arr = np.arange(12).reshape(3,4,1)
arr

array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]]])

In [31]:
arr = np.arange(12).reshape(6,2,1)
arr

array([[[ 0],
        [ 1]],

       [[ 2],
        [ 3]],

       [[ 4],
        [ 5]],

       [[ 6],
        [ 7]],

       [[ 8],
        [ 9]],

       [[10],
        [11]]])

In [33]:
from numpy import array
data = array( [[11,22,33], [44,55,66], [77,88,99]] )
data

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [34]:
X = data[ : , :-1 ]
X

array([[11, 22],
       [44, 55],
       [77, 88]])

In [35]:
X.shape

(3, 2)

In [36]:
y = data[ : , -1 ]
y

array([33, 66, 99])

In [37]:
y.shape

(3,)

In [38]:
import pandas as pd

In [39]:
pd.__version__

'1.0.5'

In [50]:
data = pd.Series( ['a','b','c'] )
data

0    a
1    b
2    c
dtype: object

In [52]:
# Indexers: loc vs iloc

data = pd.Series( ['a','b','c'], index=[1,3,5] )
data

1    a
3    b
5    c
dtype: object

In [41]:
# explicit index when indexing
data[1]

'a'

In [43]:
# implicit index when slicing
data[1:3]

3    b
5    c
dtype: object

In [44]:
data

1    a
3    b
5    c
dtype: object

In [45]:
data.loc[1]

'a'

In [47]:
data.loc[1:3]

1    a
3    b
dtype: object

In [48]:
data.iloc[1]

'b'

In [49]:
data.iloc[1:3]

3    b
5    c
dtype: object

In [54]:
data.loc[1:2]

1    a
dtype: object

In [55]:
# Indexers: loc vs iloc

data = pd.Series( ['a','b','c'], index=['A','B','C'] )
data

A    a
B    b
C    c
dtype: object

In [57]:
data.loc['A':'B']

A    a
B    b
dtype: object

In [58]:
data.loc['A':'b']

A    a
B    b
C    c
dtype: object

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Mall_Customers.csv")
df.head()

CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [3]:
df.shape

(200, 5)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   CustomerID              200 non-null    int64 
 1   Gender                  200 non-null    object
 2   Age                     200 non-null    int64 
 3   Annual Income (k$)      200 non-null    int64 
 4   Spending Score (1-100)  200 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 7.9+ KB


In [5]:
# Summary of all numeric cols

df.describe()

CustomerID         Age  Annual Income (k$)  Spending Score (1-100)
count  200.000000  200.000000          200.000000              200.000000
mean   100.500000   38.850000           60.560000               50.200000
std     57.879185   13.969007           26.264721               25.823522
min      1.000000   18.000000           15.000000                1.000000
25%     50.750000   28.750000           41.500000               34.750000
50%    100.500000   36.000000           61.500000               50.000000
75%    150.250000   49.000000           78.000000               73.000000
max    200.000000   70.000000          137.000000               99.000000

In [6]:
# Find Numeric cols

df.describe().columns

Index(['CustomerID', 'Age', 'Annual Income (k$)', 'Spending Score (1-100)'], dtype='object')

In [8]:
df.columns

Index(['CustomerID', 'Gender', 'Age', 'Annual Income (k$)',
       'Spending Score (1-100)'],
      dtype='object')

In [10]:
# Find all Categorical cols
list(set(df.columns) - set(df.describe().columns))

['Gender']

In [11]:
df['Gender'].describe()

count        200
unique         2
top       Female
freq         112
Name: Gender, dtype: object

In [12]:
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [13]:
df['Gender'].value_counts()

Female    112
Male       88
Name: Gender, dtype: int64

In [15]:
df['Gender'] == 'Female'

0      False
1      False
2       True
3       True
4       True
       ...  
195     True
196     True
197    False
198    False
199    False
Name: Gender, Length: 200, dtype: bool

In [16]:
df[ df['Gender'] == 'Female' ]

CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
5             6  Female   22                  17                      76
6             7  Female   35                  18                       6
..          ...     ...  ...                 ...                     ...
191         192  Female   32                 103                      69
193         194  Female   38                 113                      91
194         195  Female   47                 120                      16
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28

[112 rows x 5 columns]

In [22]:
# Average Annula income of females

df['Annual Income (k$)'].loc[df['Gender'] == 'Female'].mean()

59.25

In [23]:
df[ df['Gender'] == 'Female' ]['Annual Income (k$df)'].mean()

59.25

In [24]:
df.groupby('Gender').mean()

CustomerID        Age  Annual Income (k$)  Spending Score (1-100)
Gender                                                                   
Female   97.562500  38.098214           59.250000               51.526786
Male    104.238636  39.806818           62.227273               48.511364

In [25]:
df.groupby('Gender')['Age','Annual Income (k$)','Spending Score (1-100)'].mean()

<ipython-input-25-d91a4679782d>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df.groupby('Gender')['Age','Annual Income (k$)','Spending Score (1-100)'].mean()


Age  Annual Income (k$)  Spending Score (1-100)
Gender                                                       
Female  38.098214           59.250000               51.526786
Male    39.806818           62.227273               48.511364

In [26]:
df = pd.read_csv("train.csv")
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [28]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [31]:
x = df['Age'].mean()
x

29.69911764705882

In [32]:
df['Age'].fillna(x, inplace=True)

In [33]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  891.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   13.002015    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   22.000000    0.000000   
50%     446.000000    0.000000    3.000000   29.699118    0.000000   
75%     668.500000    1.000000    3.000000   35.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [34]:
df.Pclass.value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [37]:
df['Pclass'].value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [38]:
df.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [39]:
X = df.drop('Survived', axis=1)
X.head()

PassengerId  Pclass                                               Name  \
0            1       3                            Braund, Mr. Owen Harris   
1            2       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2            3       3                             Heikkinen, Miss. Laina   
3            4       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4            5       3                           Allen, Mr. William Henry   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S  
1  female  38.0      1      0          PC 17599  71.2833   C85        C  
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S  
3  female  35.0      1      0            113803  53.1000  C123        S  
4    male  35.0      0      0            373450   8.0500   NaN        S

In [40]:
y = df['Survived']
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

# Happy Learning